const fs = require('fs-jetpack')
// const unified = require('unified')
// const parse = require('remark-parse')
// const stringify = require('remark-stringify')
// const latex = require('..')
const remark = require('remark')
const recommended = require('remark-preset-lint-recommended')
const latex = require('..')
const report = require('vfile-reporter')
const frontmatter = require('remark-frontmatter')
const math = require('remark-math')

remark()
  .use(recommended)
  .use(frontmatter, ['yaml', 'toml'])
  .use(math, {inlineMathDouble: true})
  .use(latex)
  .process(fs.read('tests/fourth.md'), (error, file) => {
    console.error(report(error || file))
    // console.log(String(file))
    fs.write('tests/fourth.tex', String(file))
  })
